// Network mocking scaffold (template) — generated by dev:e2e-setup.
//
// Use page.route() to make E2E deterministic: stub flaky/3rd-party/upstream
// responses at the browser network boundary. Keep mock payloads in e2e/fixtures/
// and name them after the endpoint.
//
// API: https://playwright.dev/docs/mock  |  https://playwright.dev/docs/network

import { test, expect } from "@playwright/test";

test("renders the mocked list", async ({ page }) => {
  // Intercept the API call and fulfill it with a fixed payload.
  await page.route("**/api/v1/items", async (route) => {
    await route.fulfill({
      json: [
        { id: 1, name: "Fixed item A" },
        { id: 2, name: "Fixed item B" },
      ],
      // status / headers / body / contentType / response are also accepted.
    });
  });

  await page.goto("/items");
  await expect(page.getByRole("listitem")).toHaveCount(2);
  await expect(page.getByText("Fixed item A")).toBeVisible();
});

// ---------------------------------------------------------------------------
// Next.js / SSR / BFF CAVEAT
// ---------------------------------------------------------------------------
// page.route() intercepts requests the BROWSER makes. It does NOT see fetches
// made on the SERVER (Next.js Server Components, getServerSideProps, route
// handlers / BFF, app-router server fetches) — those run before the browser and
// never cross the page's network layer. To make server-side data deterministic:
//
//   1. E2E-only env flag — have the server return fixed responses when an
//      E2E flag is set (read at the BFF/data layer), then set it in CI:
//        if (process.env.E2E_MOCK === "1") return FIXTURE;
//
//   2. Mock the upstream the server calls (point the server at a stub host /
//      use a record-replay proxy like Playwright's own routeFromHAR for the
//      server process), not page.route.
//
//   3. Seed a deterministic test database for the server to read.
//
// Only client-side fetches (browser -> API) are mockable with page.route below.
